{% set name = "openqasm3" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/openqasm3-{{ version }}.tar.gz
  sha256: c589dc05d4ced50ca24167d14e0f2c916e717499ba0442e0ff2a3030ef312d0a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - wheel
  run:
    - python >={{ python_min }}
    - antlr4-python3-runtime
    # Only used in the parser extra but very lightweight and therefore included here
    - importlib-metadata

test:
  imports:
    - openqasm3
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Qiskit/openqasm
  summary: Reference OpenQASM AST in Python
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - BastianZim
